### ISSUE TITLE
[Build error] Missing OpenGL headers on Jetson TK1

### ISSUE THREAD

**Issue by geelen** [WebKitForWayland/cairo#1]
Hey, trying get to WebKitForWayland building as per instructions in https://github.com/WebKitForWayland/webkit

Working from a fresh installation of [Linux4Tegra](https://developer.nvidia.com/linux-tegra-rel-21), recorded all the compilation bugs and the commands to fix them [in a GIST](https://gist.github.com/geelen/33b84309461de296cafc), but am still stuck on the first step on building Cairo. The key lines of output are these:

```
checking for cairo's OpenGLESv2 surface backend feature... 
checking for glesv2... no
checking GLES2/gl2.h usability... no
checking GLES2/gl2.h presence... no
checking for GLES2/gl2.h... no
checking whether cairo's OpenGLESv2 surface backend feature could be enabled... no (glesv2.pc nor OpenGL ES 2.0 headers not found)
configure: error:  OpenGLESv2 surface backend feature could not be enabled
```

I have a feeling that the Jetson TK1's chip (Tegra K1 kepler architecture) doesn't support GLES2, given that the examples [they ship with](https://github.com/NVIDIAGameWorks/OpenGLSamples/tree/master/samples) have ES3 & GL4 but no ES2, but that's just a hunch. I tried replacing `--enable-glesv2` with `--enable-glesv3` but that didn't work either so I'm stumped. Since the Jetson supports full OpenGL 4, is it possible to build Webkit for Wayland on this device using that instead of ES2?

I wouldn't have picked the Jetson as a viable target, except that @zdobersek mentioned it in the [announcement post](http://blogs.igalia.com/zdobersek/2014/12/09/announcing-webkit-for-wayland/)

Any help would be much appreciated!

**Comment by zdobersek** [comment]
The main requirement for running on Jetson TK1 is using the open-source graphics stack. This means using a newer version of kernel, libdrm and Mesa.

The whole stack is still under development, but is functioning well enough already. It's being developed by NVIDIA, which provides a bundle of all the necessary stuff and builds it on top of Linux4Tegra:
https://github.com/NVIDIA/tegra-nouveau-rootfs

Following those instructions should provide you with a system that has all the necessary dependencies. Feel free to report any further issues you experience on top of that setup. I'll keep this issue open for a few more days, and close it if there are no additional problems.

**Comment by zdobersek** [comment]
I also skimmed your notes. The protocol for the libffi download has already been changed. As for missing packages, I'll have to add an additional script that downloads all the necessary packages.

Thanks for sharing the note.

**Comment by geelen** [comment]
Thanks for the response! I'm gonna try those instructions now and report back.

**Comment by geelen** [comment]
Hey @zdobersek thanks again for pointing me at that. I went through that process and it seemed to go fine, but I can't seem to get the screen to work when I boot up. I've left an issue agains the repo to see if I can figure out what's going on (https://github.com/NVIDIA/tegra-nouveau-rootfs/issues/3) but will push on and see if I can at least get WebkitForWayland compiling, and will let you know how I get on.

**Comment by geelen** [comment]
Ok, failing on `libinput` not being present. I'm guessing this needs to be built from source? Should it be added to the build process?

Console output here: https://gist.github.com/geelen/980128255b42f7a3bdd5

**Comment by geelen** [comment]
Hey @zdobersek, sorry to bug you, but any ideas on how to get `libinput` building given that output?

**Comment by zdobersek** [comment]
libinput 0.6.0 should definitely work, but AFAIK Ubuntu 14.04 doesn't provide it, and the version you checked out has possibly already changed a few API entrypoints.

I'll include it in the jhbuild moduleset.

**Comment by geelen** [comment]
Thanks!

**Comment by geelen** [comment]
This step now passes, and the dependencies are all built successfully! Thanks! I've opened another ticket for the compilation error against Webkit: https://github.com/WebKitForWayland/webkit/pull/6

But this issue is all done & dusted, thanks :)
